# This is a sample configuration file. Link your own file into the
# image at /filebeat/filebeat.yml to configure it for your needs.
---
filebeat.inputs:
- type: log
  paths:
    - /var/log/*.log

output.console:
  pretty: true

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
processors:
- add_cloud_metadata: ~
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'